### PR TITLE
Fix the gcloud add default parameter

### PR DESCRIPTION
**Pull request by JChord**
> aocr: error: unrecognized arguments: --job-dir

### CODE REVIEW

**Comment by emedvedev** [comment]
`--job-dir` does not belong to aocr, so it shouldn't be in the code. It's a Google Cloud parameter. The aocr counterpart is `model-dir`.

**Comment by JChord** [comment]
Gcloud somehow uses that ‘--job-dir ’ anyway, it's wired.

> master-replica-0 aocr: error: unrecognized arguments: --job-dir

**Comment by emedvedev** [comment]
That's a good point, overlooked that, sorry. :) 
Then, since `job-dir` has pretty much the same use as `model-dir`, could you just add it to the `model-dir` argument? Instead of `add_argument('--model-dir',` it should be `add_argument('--model-dir', '--job-dir',` — and then the parser will simply accept either one.

**Comment by JChord** [comment]
OK, good idea !

**Comment by emedvedev** [comment]
Awesome, merging! Thanks a lot.

**Pull request merged**
