### PR TITLE
Fix the parameters error

### PR DESCRIPTION
**Pull request by JChord**
'--model-dir' set for aocr nor gcloud

### CODE REVIEW

**Comment by emedvedev** [comment]
Thanks for the PR. Can you confirm it doesn’t work as specified in the README? What’s the error you’re getting?

**Comment by emedvedev** [comment]
Gcloud is supposed to receive it through `--job-dir`, and aocr receives it through `--model-dir`. So you are correct, but there's no mistake here, because that's exactly how it's supposed to work.

Can you give me the complete log of your attempt? I.e. the full command you're issuing and the full error you're getting.

**Comment by emedvedev** [comment]
Related to https://github.com/emedvedev/attention-ocr/pull/78: if you specify `job-dir` and `model-dir` to be the same argument, then `model-dir` can be removed from this example at all.

**Comment by JChord** [comment]
This issue can be closed. I can’t reproduce this problem.

**Comment by emedvedev** [comment]
Can you please check and confirm that after applying #78 there's no need for `model-dir` anymore?

**Comment by emedvedev** [comment]
Perfect, I'll close and remove `model-dir` from the README then. Thanks!

**Pull request closed without merging**
